# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/basic.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/basic.proto\x12\x05\x62\x61sic\"*\n\x0b\x41\x63\x63ountInfo\x12\x0c\n\x04slot\x18\x01 \x01(\x04\x12\r\n\x05value\x18\x02 \x01(\x0c\"\x16\n\x08SignedTx\x12\n\n\x02tx\x18\x01 \x01(\x0c\"A\n\x10TxStatusWithSlot\x12\x1f\n\x06status\x18\x01 \x01(\x0e\x32\x0f.basic.TxStatus\x12\x0c\n\x04slot\x18\x02 \x01(\x04\"\x07\n\x05\x45mpty\"\x16\n\x06Pubkey\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"9\n\x07Keypair\x12\x0e\n\x04seed\x18\x01 \x01(\x0cH\x00\x12\x15\n\x0bprivate_key\x18\x02 \x01(\x0cH\x00\x42\x07\n\x05input\"&\n\tProgramId\x12\x19\n\x02id\x18\x01 \x01(\x0b\x32\r.basic.Pubkey*7\n\x08TxStatus\x12\r\n\tPROCESSED\x10\x00\x12\r\n\tCONFIRMED\x10\x01\x12\r\n\tFINALIZED\x10\x02\x42\x30Z.github.com/SolmateDev/go-rust-translator/basicb\x06proto3')

_TXSTATUS = DESCRIPTOR.enum_types_by_name['TxStatus']
TxStatus = enum_type_wrapper.EnumTypeWrapper(_TXSTATUS)
PROCESSED = 0
CONFIRMED = 1
FINALIZED = 2


_ACCOUNTINFO = DESCRIPTOR.message_types_by_name['AccountInfo']
_SIGNEDTX = DESCRIPTOR.message_types_by_name['SignedTx']
_TXSTATUSWITHSLOT = DESCRIPTOR.message_types_by_name['TxStatusWithSlot']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_PUBKEY = DESCRIPTOR.message_types_by_name['Pubkey']
_KEYPAIR = DESCRIPTOR.message_types_by_name['Keypair']
_PROGRAMID = DESCRIPTOR.message_types_by_name['ProgramId']
AccountInfo = _reflection.GeneratedProtocolMessageType('AccountInfo', (_message.Message,), {
  'DESCRIPTOR' : _ACCOUNTINFO,
  '__module__' : 'proto.basic_pb2'
  # @@protoc_insertion_point(class_scope:basic.AccountInfo)
  })
_sym_db.RegisterMessage(AccountInfo)

SignedTx = _reflection.GeneratedProtocolMessageType('SignedTx', (_message.Message,), {
  'DESCRIPTOR' : _SIGNEDTX,
  '__module__' : 'proto.basic_pb2'
  # @@protoc_insertion_point(class_scope:basic.SignedTx)
  })
_sym_db.RegisterMessage(SignedTx)

TxStatusWithSlot = _reflection.GeneratedProtocolMessageType('TxStatusWithSlot', (_message.Message,), {
  'DESCRIPTOR' : _TXSTATUSWITHSLOT,
  '__module__' : 'proto.basic_pb2'
  # @@protoc_insertion_point(class_scope:basic.TxStatusWithSlot)
  })
_sym_db.RegisterMessage(TxStatusWithSlot)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'proto.basic_pb2'
  # @@protoc_insertion_point(class_scope:basic.Empty)
  })
_sym_db.RegisterMessage(Empty)

Pubkey = _reflection.GeneratedProtocolMessageType('Pubkey', (_message.Message,), {
  'DESCRIPTOR' : _PUBKEY,
  '__module__' : 'proto.basic_pb2'
  # @@protoc_insertion_point(class_scope:basic.Pubkey)
  })
_sym_db.RegisterMessage(Pubkey)

Keypair = _reflection.GeneratedProtocolMessageType('Keypair', (_message.Message,), {
  'DESCRIPTOR' : _KEYPAIR,
  '__module__' : 'proto.basic_pb2'
  # @@protoc_insertion_point(class_scope:basic.Keypair)
  })
_sym_db.RegisterMessage(Keypair)

ProgramId = _reflection.GeneratedProtocolMessageType('ProgramId', (_message.Message,), {
  'DESCRIPTOR' : _PROGRAMID,
  '__module__' : 'proto.basic_pb2'
  # @@protoc_insertion_point(class_scope:basic.ProgramId)
  })
_sym_db.RegisterMessage(ProgramId)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z.github.com/SolmateDev/go-rust-translator/basic'
  _TXSTATUS._serialized_start=295
  _TXSTATUS._serialized_end=350
  _ACCOUNTINFO._serialized_start=28
  _ACCOUNTINFO._serialized_end=70
  _SIGNEDTX._serialized_start=72
  _SIGNEDTX._serialized_end=94
  _TXSTATUSWITHSLOT._serialized_start=96
  _TXSTATUSWITHSLOT._serialized_end=161
  _EMPTY._serialized_start=163
  _EMPTY._serialized_end=170
  _PUBKEY._serialized_start=172
  _PUBKEY._serialized_end=194
  _KEYPAIR._serialized_start=196
  _KEYPAIR._serialized_end=253
  _PROGRAMID._serialized_start=255
  _PROGRAMID._serialized_end=293
# @@protoc_insertion_point(module_scope)
