# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/solana.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import basic_pb2 as proto_dot_basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/solana.proto\x12\x06solana\x1a\x11proto/basic.proto\"U\n\x10SendBatchRequest\x12\n\n\x02tx\x18\x01 \x03(\x0c\x12\x35\n\x12\x63onfirmation_level\x18\x02 \x01(\x0e\x32\x19.solana.ConfirmationLevel\"&\n\x11SendBatchResponse\x12\x11\n\tsignature\x18\x01 \x03(\x0c\"v\n\x07Genesis\x12\x1d\n\x05payer\x18\x01 \x01(\x0b\x32\x0e.basic.Keypair\x12\x1c\n\x04mint\x18\x02 \x01(\x0b\x32\x0e.basic.Keypair\x12\x1c\n\x05owner\x18\x03 \x01(\x0b\x32\r.basic.Pubkey\x12\x10\n\x08\x64\x65\x63imals\x18\x04 \x01(\x0c\"\\\n\x16InitializeTokenAccount\x12\x1b\n\x04mint\x18\x01 \x01(\x0b\x32\r.basic.Pubkey\x12%\n\rowner_account\x18\x02 \x01(\x0b\x32\x0e.basic.Keypair\"\x96\x01\n\x04Mint\x12\x1d\n\x05payer\x18\x01 \x01(\x0b\x32\x0e.basic.Keypair\x12\x1e\n\x06signer\x18\x02 \x01(\x0b\x32\x0e.basic.Keypair\x12\x1b\n\x04mint\x18\x03 \x01(\x0b\x32\r.basic.Pubkey\x12 \n\trecipient\x18\x04 \x01(\x0b\x32\r.basic.Pubkey\x12\x10\n\x08quantity\x18\x05 \x01(\x04\"i\n\rCreateAccount\x12\x1b\n\x04mint\x18\x01 \x01(\x0b\x32\r.basic.Pubkey\x12\x1c\n\x05owner\x18\x02 \x01(\x0b\x32\r.basic.Pubkey\x12\x1d\n\x05payer\x18\x03 \x01(\x0b\x32\x0e.basic.Keypair*@\n\x11\x43onfirmationLevel\x12\r\n\tPROCESSED\x10\x00\x12\r\n\tCONFIRMED\x10\x01\x12\r\n\tFINALIZED\x10\x02\x32\xb0\x02\n\tBroadcast\x12?\n\x06SendTx\x12\x18.solana.SendBatchRequest\x1a\x19.solana.SendBatchResponse\"\x00\x12-\n\nRunGenesis\x12\x0f.solana.Genesis\x1a\x0c.basic.Empty\"\x00\x12M\n\x19RunInitializeTokenAccount\x12\x1e.solana.InitializeTokenAccount\x1a\x0e.basic.Keypair\"\x00\x12;\n\x10RunCreateAccount\x12\x15.solana.CreateAccount\x1a\x0e.basic.Keypair\"\x00\x12\'\n\x07RunMint\x12\x0c.solana.Mint\x1a\x0c.basic.Empty\"\x00\x42\x31Z/github.com/SolmateDev/go-rust-translator/solanab\x06proto3')

_CONFIRMATIONLEVEL = DESCRIPTOR.enum_types_by_name['ConfirmationLevel']
ConfirmationLevel = enum_type_wrapper.EnumTypeWrapper(_CONFIRMATIONLEVEL)
PROCESSED = 0
CONFIRMED = 1
FINALIZED = 2


_SENDBATCHREQUEST = DESCRIPTOR.message_types_by_name['SendBatchRequest']
_SENDBATCHRESPONSE = DESCRIPTOR.message_types_by_name['SendBatchResponse']
_GENESIS = DESCRIPTOR.message_types_by_name['Genesis']
_INITIALIZETOKENACCOUNT = DESCRIPTOR.message_types_by_name['InitializeTokenAccount']
_MINT = DESCRIPTOR.message_types_by_name['Mint']
_CREATEACCOUNT = DESCRIPTOR.message_types_by_name['CreateAccount']
SendBatchRequest = _reflection.GeneratedProtocolMessageType('SendBatchRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDBATCHREQUEST,
  '__module__' : 'proto.solana_pb2'
  # @@protoc_insertion_point(class_scope:solana.SendBatchRequest)
  })
_sym_db.RegisterMessage(SendBatchRequest)

SendBatchResponse = _reflection.GeneratedProtocolMessageType('SendBatchResponse', (_message.Message,), {
  'DESCRIPTOR' : _SENDBATCHRESPONSE,
  '__module__' : 'proto.solana_pb2'
  # @@protoc_insertion_point(class_scope:solana.SendBatchResponse)
  })
_sym_db.RegisterMessage(SendBatchResponse)

Genesis = _reflection.GeneratedProtocolMessageType('Genesis', (_message.Message,), {
  'DESCRIPTOR' : _GENESIS,
  '__module__' : 'proto.solana_pb2'
  # @@protoc_insertion_point(class_scope:solana.Genesis)
  })
_sym_db.RegisterMessage(Genesis)

InitializeTokenAccount = _reflection.GeneratedProtocolMessageType('InitializeTokenAccount', (_message.Message,), {
  'DESCRIPTOR' : _INITIALIZETOKENACCOUNT,
  '__module__' : 'proto.solana_pb2'
  # @@protoc_insertion_point(class_scope:solana.InitializeTokenAccount)
  })
_sym_db.RegisterMessage(InitializeTokenAccount)

Mint = _reflection.GeneratedProtocolMessageType('Mint', (_message.Message,), {
  'DESCRIPTOR' : _MINT,
  '__module__' : 'proto.solana_pb2'
  # @@protoc_insertion_point(class_scope:solana.Mint)
  })
_sym_db.RegisterMessage(Mint)

CreateAccount = _reflection.GeneratedProtocolMessageType('CreateAccount', (_message.Message,), {
  'DESCRIPTOR' : _CREATEACCOUNT,
  '__module__' : 'proto.solana_pb2'
  # @@protoc_insertion_point(class_scope:solana.CreateAccount)
  })
_sym_db.RegisterMessage(CreateAccount)

_BROADCAST = DESCRIPTOR.services_by_name['Broadcast']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/github.com/SolmateDev/go-rust-translator/solana'
  _CONFIRMATIONLEVEL._serialized_start=650
  _CONFIRMATIONLEVEL._serialized_end=714
  _SENDBATCHREQUEST._serialized_start=49
  _SENDBATCHREQUEST._serialized_end=134
  _SENDBATCHRESPONSE._serialized_start=136
  _SENDBATCHRESPONSE._serialized_end=174
  _GENESIS._serialized_start=176
  _GENESIS._serialized_end=294
  _INITIALIZETOKENACCOUNT._serialized_start=296
  _INITIALIZETOKENACCOUNT._serialized_end=388
  _MINT._serialized_start=391
  _MINT._serialized_end=541
  _CREATEACCOUNT._serialized_start=543
  _CREATEACCOUNT._serialized_end=648
  _BROADCAST._serialized_start=717
  _BROADCAST._serialized_end=1021
# @@protoc_insertion_point(module_scope)
