# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/solana-net.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/solana-net.proto\x12\tsolananet\"X\n\x10SendBatchRequest\x12\n\n\x02tx\x18\x01 \x03(\x0c\x12\x38\n\x12\x63onfirmation_level\x18\x02 \x01(\x0e\x32\x1c.solananet.ConfirmationLevel\"&\n\x11SendBatchResponse\x12\x11\n\tsignature\x18\x01 \x03(\x0c*@\n\x11\x43onfirmationLevel\x12\r\n\tPROCESSED\x10\x00\x12\r\n\tCONFIRMED\x10\x01\x12\r\n\tFINALIZED\x10\x02\x32R\n\tBroadcast\x12\x45\n\x06SendTx\x12\x1b.solananet.SendBatchRequest\x1a\x1c.solananet.SendBatchResponse\"\x00\x42\x34Z2github.com/SolmateDev/go-rust-translator/solananetb\x06proto3')

_CONFIRMATIONLEVEL = DESCRIPTOR.enum_types_by_name['ConfirmationLevel']
ConfirmationLevel = enum_type_wrapper.EnumTypeWrapper(_CONFIRMATIONLEVEL)
PROCESSED = 0
CONFIRMED = 1
FINALIZED = 2


_SENDBATCHREQUEST = DESCRIPTOR.message_types_by_name['SendBatchRequest']
_SENDBATCHRESPONSE = DESCRIPTOR.message_types_by_name['SendBatchResponse']
SendBatchRequest = _reflection.GeneratedProtocolMessageType('SendBatchRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDBATCHREQUEST,
  '__module__' : 'proto.solana_net_pb2'
  # @@protoc_insertion_point(class_scope:solananet.SendBatchRequest)
  })
_sym_db.RegisterMessage(SendBatchRequest)

SendBatchResponse = _reflection.GeneratedProtocolMessageType('SendBatchResponse', (_message.Message,), {
  'DESCRIPTOR' : _SENDBATCHRESPONSE,
  '__module__' : 'proto.solana_net_pb2'
  # @@protoc_insertion_point(class_scope:solananet.SendBatchResponse)
  })
_sym_db.RegisterMessage(SendBatchResponse)

_BROADCAST = DESCRIPTOR.services_by_name['Broadcast']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z2github.com/SolmateDev/go-rust-translator/solananet'
  _CONFIRMATIONLEVEL._serialized_start=167
  _CONFIRMATIONLEVEL._serialized_end=231
  _SENDBATCHREQUEST._serialized_start=37
  _SENDBATCHREQUEST._serialized_end=125
  _SENDBATCHRESPONSE._serialized_start=127
  _SENDBATCHRESPONSE._serialized_end=165
  _BROADCAST._serialized_start=233
  _BROADCAST._serialized_end=315
# @@protoc_insertion_point(module_scope)
